### PR TITLE
Use event payload to extract tag_name on release/prerelease

### LINKED ISSUE #19: Error building image with the release & pre-release events
### Bug description
Suppose a developer triggers the release event from a branch outside of `main`, for example. If he wants to patch a previous version, the action is building the image with the `lastRelease` resolved by GitHub, which doesn't have to correspond with the release currently generated.

Because of this, we found that a new patch release 11.6.3.1 generated is built with the image tag 13.0.7 (the lastRelease resolved by GitHub), causing the image contains the code of the 11.6.3.1 but with the tag 13.0.7!.

### Expected behavior
When the image build is triggered from the release or pre-release event, we can't check GitHub for the last release generated (see https://github.com/prefapp/action-flavour-images-matrix-generator/blob/main/utils/ImagesCalculator.js#L26-L61)  as it may return an incorrect version.

We must extract this information directly from the [release event payload](https://docs.github.com/en/developers/webhooks-and-events/webhooks/webhook-events-and-payloads#release):

image

### PR DESCRIPTION
**Pull request by frmadem**
closes #19

### CODE REVIEW

File: utils/ImagesCalculator.js [hunk 1]
```diff
@@ -25,38 +24,42 @@ module.exports = async function(action_type, ctx){
...
   function __prerelease(octokit, ctx){
 
-    return octokit.rest.repos.listReleases({
-    
-      owner: ctx.owner,
+    return ctx.triggered_event.tag_name
+
+    //return octokit.rest.repos.listReleases({
+    //
+    //  owner: ctx.owner,
```
Comment (alambike) [inline utils/ImagesCalculator.js:49]: please, remove these comments.

**Review by alambike — APPROVED** [review]
